### ISSUE TITLE
 The function parameter contains Object type which is not supported

### ISSUE THREAD

**Issue by LogikMeister** [supercoderlee/node-pyrunner#1]
- PyRunner Version

>  1.0.5

- Clear and concise description of the problem

> Currently, the node-pyrunner module only supports string and number parameter types for calling functions. If an Object is passed in, a TypeError will occur. It can only be parsed in a Python script after passing in JSON. 

> 

> 目前，node-pyrunner 模块仅支持调用函数的字符串和数字参数类型。如果传入一个Object，就会出现TypeError。只能传入JSON后才能在Python脚本中解析。

- Suggested solution

> Can add Object support in the N-API module through serialization/deserialization？

> 

> 能否通过序列化/反序列化在 N-API 模块中添加 Object 支持。
>

**Comment by hileez** [comment]
后期会增加函数调用时参数和返回值的类型。
