### ISSUE TITLE
如何引入第三方python包

### ISSUE THREAD

**Issue by DawnLou** [supercoderlee/node-pyrunner#3]
请问如何引入第三方的python包 比如numpy

**Comment by DawnLou** [comment]
是需要把site-packages拷贝过来么？

**Comment by hileez** [comment]
使用第三方pip模块，可以在当前NPM项目中创建pyscript目录作为普通python项目进行管理，
在该目录下使用`python -m venv venv`命令创建venv虚拟环境，在激活情况下pip的模块将会安装在该venv环境中，
node-pyrunner将`/pyscript/venv/Lib/site-packages`路径作为默认的虚拟环境模块路径搜索并使用模块，

另外，也可以通过config配置模块搜索路径，例如：
```
const pyrunner = require('node-pyrunner')
// 模块搜索路径配置项，添加搜索路径
pyrunner.config['module_search_paths'].push('./pyscript');
// 虚拟环境配置项，具体到site-packages目录
pyrunner.config['pythonpath_env'] = './pyscript/venv/Lib/site-packages';
// 解释器安装目录，默认为当前项目内置解释器即/python/win32/x64/3.10.10目录，因此解释器内置标准模块都是可以使用的
pyrunner.config['python_home'] = 'Python解释器所在目录'
```
> 建议使用绝对路径配置，避免electron打包后的相对路径问题。

你也可以参考这个项目，快速创建应用：
https://github.com/supercoderlee/node-pyrunner-quick-start

**Comment by 905968561** [comment]
我按照你的方法设置了pythonpath_env，并且在venv中下载pandas模组，但是在app.py中 import pandas仍然会报错Segmentation fault (core dumped) 我确保是这里的问题
`pyrunner.config['pythonpath_env'] = '/home/zjc/HelloRpcServer/HelloRpcServer/pyscript/venv/lib/python3.10/site-packages';
//pyrunner.config['python_home']='/data/tars/tarsnode-data/Hello.HelloRpcServer/bin/src/tarspythpn'
pyrunner.config['python_home']='/home/zjc/RpcServer/RpcServer/tarspython'
pyrunner.config['program_name']='python3'
pyrunner.config['module_search_paths'].push('./pyscript');`

**Comment by 905968561** [comment]
pandas  numpy sklearn这些包导入后会报
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
