### ISSUE TITLE
Error: Cannot find module './addons/3.10.10/darwin/arm64/pyrunner'

### ISSUE THREAD

**Issue by changyongyong** [supercoderlee/node-pyrunner#5]
可以做一个mac m1的arm64包吗

**Comment by hileez** [comment]
@changyongyong Arm架构macos系统目前还没有适配，可能要过段时间。

**Comment by pengten** [comment]
> @changyongyong Arm架构macos系统目前还没有适配，可能要过段时间。

适配工作需要做些什么？我们可以集合大家力量一起来完成，我们知道现在arm架构已经是大部分企业的办公首选
