### ISSUE TITLE
./python/win32/x64/3.10.10，如何初始化这个目录的内容呢？

### ISSUE THREAD

**Issue by yushuohuanxiu** [supercoderlee/node-pyrunner#7]
有什么最佳指南来初始化这个目录的内容吗？而且windows和linux下的路径和内容都不同吧？
这个目录可以被文档中的【Dynamic link library | 动态链接库】这一章节的介绍内容替代吗？
这个环境基础配置，可以直接封装在node-pyrunner模块库中吗？使用会方便很多的！

**Comment by supercoderlee** [comment]
`./python/win32/x64/3.10.10`这是node-pyrunner默认集成解释器的目录，但是解释器需要自己集成在这个目录中，win32/x64对应的是目标平台和架构，参考https://github.com/supercoderlee/node-pyrunner-quick-start，这个项目是已经集成了windows的python解释器，另外你也可以修改node-pyrunner初始化配置config的python_home属性来指定任意目录下的python3.10解释器，初始化配置可以配置解释器路径、模块搜索路径等；
你说的“【Dynamic link library | 动态链接库】这一章节”是否是指使用pyenv来管理python环境？node-python使用的解释器可以在操作系统任意目录中，只需要初始化配置时配置config中的属性（关键是python_home）目的是python需要标准模块，但是前提是必须能让node-python加载python3.dll和python310.dll动态链接库，所以建议把这两个动态库文件拷贝到项目目录中（参考https://github.com/supercoderlee/node-pyrunner-quick-start）。
node-pyrunner因为是跨平台的npm模块，如果集成所有平台的解释器体积会很大，为了减小体积也考虑到有的用户不需要集成python解释器而是动态安装python解释器，所以就没有把各个平台的解释器集成在npm模块中。

**Comment by hileez** [comment]
`./python/win32/x64/3.10.10`这是node-pyrunner默认集成解释器的目录，但是解释器需要自己集成在这个目录中，win32/x64对应的是目标平台和架构，参考[node-pyrunner-quick-start](https://github.com/supercoderlee/node-pyrunner-quick-start)，这个项目是已经集成了windows的python解释器，另外你也可以修改node-pyrunner初始化配置config的python_home属性来指定任意目录下的python3.10解释器，初始化配置可以配置解释器路径、模块搜索路径等；
你说的“【Dynamic link library | 动态链接库】这一章节”是否是指使用pyenv来管理python环境？node-python使用的解释器可以在操作系统任意目录中，只需要初始化配置时配置config中的属性（关键是python_home）目的是python需要标准模块，但是前提是必须能让node-python加载python3.dll和python310.dll动态链接库，所以建议把这两个动态库文件拷贝到项目目录中（参考[node-pyrunner-quick-start](https://github.com/supercoderlee/node-pyrunner-quick-start)）。
node-pyrunner因为是跨平台的npm模块，如果集成所有平台的解释器体积会很大，为了减小体积也考虑到有的用户不需要集成python解释器而是动态安装python解释器，所以就没有把各个平台的解释器集成在npm模块中。
